services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: client-container
    stdin_open: true
    tty: true
    environment:
      - TO_HOST=server
      - TO_PORT=1804
    depends_on:
      server:
        condition: service_healthy

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    container_name: server-container
    ports:
      - "1804:1804"
    healthcheck:
      test: [ "CMD", "pgrep", "java" ]
      interval: 10s
      retries: 3
    tty: true
    volumes:
      - saved_data:/server/saved_dir

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "ticketControllerDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
    -   ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  saved_data:

